language: haskell


env:
 - GHCVER=7.6.3
 - GHCVER=7.8.3
 - GHCVER=head

matrix:
  allow_failures:
   - env: GHCVER=head





# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install libblas-dev liblapack-dev
 - travis_retry sudo apt-get install cabal-install-head ghc-$GHCVER-prof ghc-$GHCVER-dyn happy
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - sudo /opt/ghc/$GHCVER/bin/ghc-pkg recache
 - /opt/ghc/$GHCVER/bin/ghc-pkg recache --user
 - cabal-head update
 - cabal-head install --only-dependencies --enable-tests --enable-benchmarks

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - cabal-head configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
 - cabal-head build   # this builds all libraries and executables (including tests/benchmarks)
 - cabal-head test  --show-details=always
 - cabal-head check
 - cabal-head sdist   # tests that a source-distribution can be generated

# The following scriptlet checks that the resulting source distribution can be built & installed
 - function install_from_tarball {
   export SRC_TGZ=$(cabal-head info . | awk '{print $2 ".tar.gz";exit}') ;
   if [ -f "dist/$SRC_TGZ" ]; then
      cabal-head install "dist/$SRC_TGZ";
   else
      echo "expected 'dist/$SRC_TGZ' not found";
      exit 1;
   fi
   }
 - install_from_tarball



notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#numerical-haskell"
      - "irc.freenode.org#numerical"
      - "irc.freenode.org#wellposed"
    skip_join: true
    template:
      - "\x0313 hBLAS \x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
